apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: replicas-test
  name: replicas-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replicas-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: replicas-test
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
